# what language the build will be configured for
language: python

# note that all of the versions listed will be tried
python:
  - "3.5"
  - "3.6"

# what branches should be evaluated
branches:
  only:
    - master

# list of commands to run to setup the environment
install:
  - pip install coverage
  - pip install coveralls
  - pip install flake8
  - pip install -r requirements.txt
  - pip install -U scikit-learn
  - pip install -U spacy
  - pip install chemdataextractor
  - cde data download

# a list of commands to run before the main script
before_script:
  - "flake8 paper-parser"

script:
  - coverage run -m unittest discover

  # generate a coverage report to send to back to user
#after_success:
