# what language the build will be configured for
language: python

# note that all of the versions listed will be tried
python:
  - "3.5"
  - "3.6"

# what branches should be evaluated
branches:
  only:
    - master

# list of commands to run to setup the environment
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -c anaconda pytest
  - conda install scikit-learn
  - conda install -c chemdataextractor chemdataextractor
  - conda install -c conda-forge spacy
  - cde data download

# a list of commands to run before the main script
#before_script:

script:
  - pytest

  # generate a coverage report to send to back to user
#after_success:
